<?php

namespace Database\Seeders;

use App\Models\Master\Departments;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JabatanSeeder extends Seeder
{
    public function run()
    {
        // Ambil department IDs
        $departments = [
            'pendidikan' => Departments::where('department', 'PENDIDIKAN')->first()?->id,
            'muamalat' => Departments::where('department', 'MUAMALAT')->first()?->id,
            'hr_gs' => Departments::where('department', 'HR-GS')->first()?->id,
            'bkmd' => Departments::where('department', 'BKMD')->first()?->id,
        ];

        $positions = [
            // Top Managerial (4B - 4E)
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Direktur Pendidikan',
                'kode_jabatan' => 'TM-PD-01',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'top_managerial',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Direktur Muamalat',
                'kode_jabatan' => 'TM-MM-01',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'top_managerial',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['hr_gs'],
                'nama_jabatan' => 'Manager HR-GS',
                'kode_jabatan' => 'TM-HR-01',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'top_managerial',
                'is_active' => true,
            ],
            
            // Middle Manager (3D - 4A)
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Kabid. Kurikulum',
                'kode_jabatan' => 'MM-PD-01',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'middle_manager',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Kabid. Penjamin Mutu dan Sumber Daya',
                'kode_jabatan' => 'MM-PD-02',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'middle_manager',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Kepala Sekolah',
                'kode_jabatan' => 'MM-PD-03',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'middle_manager',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Manager BMT',
                'kode_jabatan' => 'MM-MM-01',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'middle_manager',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Manager Sektor Riil',
                'kode_jabatan' => 'MM-MM-02',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'middle_manager',
                'is_active' => true,
            ],
            
            // Supervisor (3C - 3D)
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Staf Ahli Al-Qur\'an',
                'kode_jabatan' => 'SV-PD-01',
                'jenis_jabatan' => 'fungsional',
                'level_jabatan' => 'supervisor',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Staf Ahli Pengembangan Karakter Islami',
                'kode_jabatan' => 'SV-PD-02',
                'jenis_jabatan' => 'fungsional',
                'level_jabatan' => 'supervisor',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Wakil Kepala Sekolah',
                'kode_jabatan' => 'SV-PD-03',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'supervisor',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Koor. Al-Qur\'an',
                'kode_jabatan' => 'SV-PD-04',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'supervisor',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Kepala Laboran',
                'kode_jabatan' => 'SV-PD-05',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'supervisor',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Kepala Tata Usaha',
                'kode_jabatan' => 'SV-PD-06',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'supervisor',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Kepala Pustaka',
                'kode_jabatan' => 'SV-PD-07',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'supervisor',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Kepala Bagian',
                'kode_jabatan' => 'SV-MM-01',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'supervisor',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Kepala Cabang',
                'kode_jabatan' => 'SV-MM-02',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'supervisor',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Kepala Toko',
                'kode_jabatan' => 'SV-MM-03',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'supervisor',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Koordinator Keuangan',
                'kode_jabatan' => 'SV-MM-04',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'supervisor',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Cheff',
                'kode_jabatan' => 'SV-MM-05',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'supervisor',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['hr_gs'],
                'nama_jabatan' => 'Koord. Procurement dan Sarana',
                'kode_jabatan' => 'SV-HR-01',
                'jenis_jabatan' => 'struktural',
                'level_jabatan' => 'supervisor',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['bkmd'],
                'nama_jabatan' => 'Wakil Imam Mesjid',
                'kode_jabatan' => 'SV-BK-01',
                'jenis_jabatan' => 'fungsional',
                'level_jabatan' => 'supervisor',
                'is_active' => true,
            ],
            
            // Staf (3A - 3C)
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Guru Senior',
                'kode_jabatan' => 'ST-PD-01',
                'jenis_jabatan' => 'fungsional',
                'level_jabatan' => 'staff',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Wali Kelas',
                'kode_jabatan' => 'ST-PD-02',
                'jenis_jabatan' => 'fungsional',
                'level_jabatan' => 'staff',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Guru Bidang Studi',
                'kode_jabatan' => 'ST-PD-03',
                'jenis_jabatan' => 'fungsional',
                'level_jabatan' => 'staff',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Manajemen Adm. Pendidikan',
                'kode_jabatan' => 'ST-PD-04',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'staff',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Laboran',
                'kode_jabatan' => 'ST-PD-05',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'staff',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Account Officer',
                'kode_jabatan' => 'ST-MM-01',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'staff',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Internal Audit',
                'kode_jabatan' => 'ST-MM-02',
                'jenis_jabatan' => 'fungsional',
                'level_jabatan' => 'staff',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Adm Pembiayaan',
                'kode_jabatan' => 'ST-MM-03',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'staff',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Back office',
                'kode_jabatan' => 'ST-MM-04',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'staff',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Cook',
                'kode_jabatan' => 'ST-MM-05',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'staff',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['hr_gs'],
                'nama_jabatan' => 'HR Spesialis Adm',
                'kode_jabatan' => 'ST-HR-01',
                'jenis_jabatan' => 'fungsional',
                'level_jabatan' => 'staff',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['hr_gs'],
                'nama_jabatan' => 'HR Spesialis Rekrutmen',
                'kode_jabatan' => 'ST-HR-02',
                'jenis_jabatan' => 'fungsional',
                'level_jabatan' => 'staff',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['hr_gs'],
                'nama_jabatan' => 'Pemeliharaan Sarana dan Aset',
                'kode_jabatan' => 'ST-HR-03',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'staff',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['hr_gs'],
                'nama_jabatan' => 'Staf IT Hardware',
                'kode_jabatan' => 'ST-HR-04',
                'jenis_jabatan' => 'fungsional',
                'level_jabatan' => 'staff',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['hr_gs'],
                'nama_jabatan' => 'Staf IT Application',
                'kode_jabatan' => 'ST-HR-05',
                'jenis_jabatan' => 'fungsional',
                'level_jabatan' => 'staff',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['hr_gs'],
                'nama_jabatan' => 'Pengelola TPA',
                'kode_jabatan' => 'ST-HR-06',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'staff',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['bkmd'],
                'nama_jabatan' => 'Bendahara & Operasional',
                'kode_jabatan' => 'ST-BK-01',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'staff',
                'is_active' => true,
            ],
            
            // Staf Operasional (2C - 3A)
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Tata Usaha',
                'kode_jabatan' => 'SO-PD-01',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'staff_operasional',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Pustakawan',
                'kode_jabatan' => 'SO-PD-02',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'staff_operasional',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Teller',
                'kode_jabatan' => 'SO-MM-01',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'staff_operasional',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Customer Service',
                'kode_jabatan' => 'SO-MM-02',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'staff_operasional',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Maal ; Keuangan',
                'kode_jabatan' => 'SO-MM-03',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'staff_operasional',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Stock Keeper Dapur',
                'kode_jabatan' => 'SO-MM-04',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'staff_operasional',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['hr_gs'],
                'nama_jabatan' => 'Staf Pemeliharaan Kebersihan Lingkungan',
                'kode_jabatan' => 'SO-HR-01',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'staff_operasional',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['hr_gs'],
                'nama_jabatan' => 'Staf Procurement',
                'kode_jabatan' => 'SO-HR-02',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'staff_operasional',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['hr_gs'],
                'nama_jabatan' => 'Perawat',
                'kode_jabatan' => 'SO-HR-03',
                'jenis_jabatan' => 'fungsional',
                'level_jabatan' => 'staff_operasional',
                'is_active' => true,
            ],
            
            // Operator (2A - 2B)
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Janitor',
                'kode_jabatan' => 'OP-PD-01',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'operator',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Penjaga Toilet',
                'kode_jabatan' => 'OP-PD-02',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'operator',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Petugas Taman',
                'kode_jabatan' => 'OP-PD-03',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'operator',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Kasir',
                'kode_jabatan' => 'OP-MM-01',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'operator',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Operator Fotocopy',
                'kode_jabatan' => 'OP-MM-02',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'operator',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Pengadaan Barang Warung',
                'kode_jabatan' => 'OP-MM-03',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'operator',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Helper',
                'kode_jabatan' => 'OP-MM-04',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'operator',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Dishwasher',
                'kode_jabatan' => 'OP-MM-05',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'operator',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['hr_gs'],
                'nama_jabatan' => 'Perbaikan Sarana',
                'kode_jabatan' => 'OP-HR-01',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'operator',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['hr_gs'],
                'nama_jabatan' => 'Ekspedisi',
                'kode_jabatan' => 'OP-HR-02',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'operator',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['hr_gs'],
                'nama_jabatan' => 'Driver',
                'kode_jabatan' => 'OP-HR-03',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'operator',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['hr_gs'],
                'nama_jabatan' => 'Petugas Taman',
                'kode_jabatan' => 'OP-HR-04',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'operator',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['hr_gs'],
                'nama_jabatan' => 'Perbaikan Komputer dan Jaringan',
                'kode_jabatan' => 'OP-HR-05',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'operator',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['bkmd'],
                'nama_jabatan' => 'Janitor',
                'kode_jabatan' => 'OP-BK-01',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'operator',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['bkmd'],
                'nama_jabatan' => 'Tenaga Kebersihan',
                'kode_jabatan' => 'OP-BK-02',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'operator',
                'is_active' => true,
            ],
            
            // PHL
            [
                'department_id' => $departments['pendidikan'],
                'nama_jabatan' => 'Pengasuh TPA',
                'kode_jabatan' => 'PHL-PD-01',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'phl',
                'is_active' => true,
            ],
            [
                'department_id' => $departments['muamalat'],
                'nama_jabatan' => 'Pramusaji',
                'kode_jabatan' => 'PHL-MM-01',
                'jenis_jabatan' => 'pelaksana',
                'level_jabatan' => 'phl',
                'is_active' => true,
            ],
            
            // Jabatan Khusus (4B - 4E)
            [
                'department_id' => $departments['bkmd'],
                'nama_jabatan' => 'Imam Mesjid',
                'kode_jabatan' => 'JK-BK-01',
                'jenis_jabatan' => 'fungsional',
                'level_jabatan' => 'jabatan_khusus',
                'is_active' => true,
            ],
        ];

        foreach ($positions as $position) {
            DB::table('master_jabatan')->insert([
                'department_id' => $position['department_id'],
                'nama_jabatan' => $position['nama_jabatan'],
                'kode_jabatan' => $position['kode_jabatan'],
                'jenis_jabatan' => $position['jenis_jabatan'],
                'level_jabatan' => $position['level_jabatan'],
                'is_active' => $position['is_active'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}